on: push
name: test app CI
jobs:
  checks:
    name: run
    runs-on: macos-15  # Use macOS Sonoma (14), which should be more compatible with newer Xcode/Swift tools
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: "Select Xcode version"
      uses: BoundfoxStudios/action-xcode-select@v1
      with:
        version: "16.0"  # Use a more specific version that's known to be available on macOS-14
    
    - name: setup bazel
      uses: bazel-contrib/setup-bazel@0.14.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
        version: 7.1.0

    - name: Debug environment
      run: |
        xcodebuild -version
        xcrun --sdk iphoneos --show-sdk-version
        xcrun --sdk iphoneos --show-sdk-path
        bazel version
        xcrun simctl boot 899262C6-E5C3-4BE6-A728-AC9ADC2AB91C

    
    - name: testMessengerTab
      run: |
        bazel test //LarkCloneTests/MessengerTabTest:MessengerTabTest --test_output=errors || echo "Tests Messenger failed"
    
    - name: testMailTab
      run: |
        bazel test //LarkCloneTests/MailTabTest:MailTabTest --test_output=errors || echo "Tests Mail failed"

    - name: MessengerTest log
      uses: actions/upload-artifact@v4
      with:
        name: MessengerTest.log
        path: bazel-out/darwin_arm64-fastbuild/testlogs/LarkCloneTests/MessengerTabTest/MessengerTabTest/test.log
        if-no-files-found: warn

    - name: MailTest log
      uses: actions/upload-artifact@v4
      with:
        name: MailTest.log
        path: bazel-out/darwin_arm64-fastbuild/testlogs/LarkCloneTests/MailTabTest/MailTabTest/test.log
        if-no-files-found: warn



